# Generated by Django 4.2.29 on 2026-03-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_schedule_and_vote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='allowed_weekdays',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='poll',
            name='daily_end_hour',
            field=models.PositiveSmallIntegerField(default=17),
        ),
        migrations.AddField(
            model_name='poll',
            name='daily_start_hour',
            field=models.PositiveSmallIntegerField(default=9),
        ),
    ]
